---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags
  environments_path: test/environments
  client_rb:
    environment: skellington
  attributes:
    user: skellington
    envbuilder:
      base_dir: /home/skellington
      owner: skellington
      group: skellington

platforms:
  - name: ubuntu-14.04


suites:
  - name: skellington
    run_list:
      - recipe[skellington::default]

  - name: thighbone
    run_list:
      - recipe[skellington::default]
      - recipe[skellington::vhost_tester]
    attributes:
      ruby-ng:
        ruby_version: 1.9.3
      fully_qualified_domain_name: thighbone.theodi.org

  - name: kneecap
    run_list:
      - recipe[skellington::default]
      - recipe[skellington::vhost_tester]
    attributes:
      fully_qualified_domain_name: kneecap.theodi.org
      ruby-ng:
        ruby_version: 2.2
      deployment:
        nginx:
          prefix: staging

  - name: sternum
    run_list:
      - recipe[skellington::dbconfig]
    attributes:
      user: shoulder_blade
      fully_qualified_domain_name: sternum.io

  - name: cranium
    run_list:
      - recipe[skellington::dbconfig]
    attributes:
      user: cranium
      fully_qualified_domain_name: cranium.io
      mysql:
        username: skeletor
