---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags
  environments_path: test/environments
  attributes:
    user: skellington
    envbuilder:
      base_dir: /home/skellington
      owner: skellington
      group: skellington

platforms:
  - name: ubuntu-14.04


suites:
  - name: skellington
    provisioner:
      client_rb:
        environment: skellington
    run_list:
      - recipe[skellington::default]
    attributes:

  - name: thighbone
    run_list:
      - recipe[skellington::default]
    attributes:
      ruby-ng:
        ruby_version: 1.9.3

  - name: kneecap
    run_list:
      - recipe[skellington::default]
    attributes:
      ruby-ng:
        ruby_version: 2.2
